server:
  port: 8080

spring:
  profiles:
    active: dev
  ai:
      dashscope:
        api-key: ${SPRING_AI_DASH_SCOPE_API_KEY}
        chat:
          options:
            model: qwen-max
  data:
      redis:
        host: ${SPRING_DATA_REDIS_HOST}
        port: ${SPRING_DATA_REDIS_PORT}
        database: ${SPRING_DATA_REDIS_DATABASE}

search-api:
    api-key: ${SPRING_SEARCH_API_KEY}

zhipu:
  api-key: ${ZHIPU_API_KEY}

logging:
  level:
    org.springframework.ai: DEBUG