server:
  port: 8080

spring:
   ai:
     dashscope:
       api-key: <Your ApiKey>
       chat:
         options:
           model: qwen-max

search-api:
    api-key: <Your ApiKey>

logging:
  level:
    org.springframework.ai: DEBUG